version: 0.2

env:
    variables:
        AWS_DEFAULT_REGION: 'ap-northeast-1'
        IMAGE_NAME: 'onlinecode_app'
        CONTAINER_NAME: 'code'

phases:
    pre_build:
        commands:
            - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
            - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
            - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
    build:
        commands:
            - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
    post_build:
        commands:
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - printf '[{"name":"code","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
