version: "3.7"

services:
    app:
        container_name: code
        # image: "009554248005.dkr.ecr.ap-northeast-1.amazonaws.com/onlinecode_app"
        build: .
        tty: true
        ports:
            - "10000:10000"
        command: ./main
        volumes:
            - ./:/go/src/work
            - /var/run/docker.sock:/var/run/docker.sock
