name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # terraform install
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    
    # terraform fmt
    - name: Terraform Format
      run: terraform fmt -recursive -check

    # terraform init
    - name: Terraform Validation
      working-directory: ./terraform
      run: |
        terraform init
        terraform workspace select stg
        terraform validate
        terraform plan -no-color

    - name: Comment
      uses: actions/github-script@v3.0.0
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          #### Terraform Plan: \`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })